name: docveda_app
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

#---------------------------- PACKAGES ----------------------

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8
  get: ^4.7.2
  uuid: ^3.0.7
  intl: ^0.20.2
  logger: ^2.5.0
  url_launcher: ^6.3.1
  get_storage: ^2.1.1
  flutter_native_splash: ^2.4.4
  flutter_screenutil: ^5.9.0
  fl_chart: ^0.65.0
  shared_preferences: ^2.2.2
  encrypt: ^5.0.3
  http: ^0.13.4
  pkce: ^1.0.0
  crypto: ^3.0.1
  firebase_core: ^3.13.0
  firebase_analytics: ^11.4.5
  firebase_messaging: ^15.2.5
  app_settings: ^6.1.1
  flutter_dotenv: ^5.2.1
  flutter_secure_storage:
    git:
      url: https://github.com/mogol/flutter_secure_storage.git
      ref: master
      path: flutter_secure_storage
  flutter_local_notifications: ^18.0.1
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.3"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app-logo.png"

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/videos/
    - assets/fonts/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Bold.ttf
        - asset: assets/fonts/Manrope-ExtraBold.ttf
        - asset: assets/fonts/Manrope-ExtraLight.ttf
        - asset: assets/fonts/Manrope-Light.ttf
        - asset: assets/fonts/Manrope-Medium.ttf
        - asset: assets/fonts/Manrope-Regular.ttf
        - asset: assets/fonts/Manrope-SemiBold.ttf

          # style: italic
        #- family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
