// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvosaY42ZfUmzRTrD_ncXpnIvbqb68MPM',
    appId: '1:463411523741:web:624e2de739d6a7aa366474',
    messagingSenderId: '463411523741',
    projectId: 'docveda-app',
    authDomain: 'docveda-app.firebaseapp.com',
    storageBucket: 'docveda-app.firebasestorage.app',
    measurementId: 'G-F3GC2HPK9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHYPdqGLmD6uXCoUPKT8slGkAsWc-kxlI',
    appId: '1:463411523741:android:4b07f3091cf26250366474',
    messagingSenderId: '463411523741',
    projectId: 'docveda-app',
    storageBucket: 'docveda-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG8fVfy5oewJ8-p4B2jCiF76L4Om0ieG4',
    appId: '1:463411523741:ios:641040d8d63fe22c366474',
    messagingSenderId: '463411523741',
    projectId: 'docveda-app',
    storageBucket: 'docveda-app.firebasestorage.app',
    iosBundleId: 'com.example.docvedaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG8fVfy5oewJ8-p4B2jCiF76L4Om0ieG4',
    appId: '1:463411523741:ios:641040d8d63fe22c366474',
    messagingSenderId: '463411523741',
    projectId: 'docveda-app',
    storageBucket: 'docveda-app.firebasestorage.app',
    iosBundleId: 'com.example.docvedaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvosaY42ZfUmzRTrD_ncXpnIvbqb68MPM',
    appId: '1:463411523741:web:b4c36b0b45ecf142366474',
    messagingSenderId: '463411523741',
    projectId: 'docveda-app',
    authDomain: 'docveda-app.firebaseapp.com',
    storageBucket: 'docveda-app.firebasestorage.app',
    measurementId: 'G-7JRR713NQT',
  );
}
